variable "vpc_id" {}
variable "vpc_cidr_block" {}
variable "avail_zone_1" {}
variable "avail_zone_2" {}
variable "avail_zone_3" {}
variable "env_prefix" {}
variable "my_ip" {}
variable "instance_type" {}
variable "public_key_location" {}
variable "PubSub1Cidr" {}
variable "PubSub2Cidr" {}
variable "PubSub3Cidr" {}
variable "PrivSub1Cidr" {}
variable "PrivSub2Cidr" {}
variable "PrivSub3Cidr" {}
variable "ami" {}
variable "db_user" {}
variable "db_password" {}
variable "db_name" {}
variable "instance_count" {}
variable "rmq_user" {}
variable "rmq_pass" {}
variable "instance_class" {}
variable "node_type" {}
variable "host_instance_type" {}
variable "USERNAME" {}
variable "PRIV_KEY_PATH" {}